export const ActionTypes = {
  SET_SEARCH: "SET_SEARCH",
  SET_CHANNELS: "SET_CHANNELS",
  MORE_CHANNELS: "MORE_CHANNELS",
  RESET_CHANNELS: "RESET_CHANNEL",
  SELECT_CHANNEL: "SELECT_CHANNEL",
  OPEN_MODAL: "OPEN_MODAL",
};
